// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchulApp.DataAccess;

#nullable disable

namespace SchulApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SchulApp.Models.Dokument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Abgegeben")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dateipfad")
                        .HasColumnType("TEXT");

                    b.Property<int>("FachId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Frist")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FachId");

                    b.HasIndex("Frist");

                    b.ToTable("Dokument", (string)null);
                });

            modelBuilder.Entity("SchulApp.Models.Fach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Erstellt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lehrperson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.ToTable("Fach", (string)null);
                });

            modelBuilder.Entity("SchulApp.Models.Dokument", b =>
                {
                    b.HasOne("SchulApp.Models.Fach", "Fach")
                        .WithMany("Dokumente")
                        .HasForeignKey("FachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fach");
                });

            modelBuilder.Entity("SchulApp.Models.Fach", b =>
                {
                    b.Navigation("Dokumente");
                });
#pragma warning restore 612, 618
        }
    }
}
